# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20160715_0028'),
        ('boat_booking', '0002_auto_20170122_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='schedule.Event'),
        ),
    ]
