# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat_booking', '0003_booking_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='name',
            field=models.TextField(default='B\xe5ten'),
            preserve_default=False,
        ),
    ]
