# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat_booking', '0004_boat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='map_image',
            field=models.ImageField(default='images/no-img.jpg', upload_to='images/'),
        ),
    ]
